"use client";

interface ReportFooterProps {
  className?: string;
}

export default function ReportFooter({ className = "" }: ReportFooterProps) {
  return (
    <div className={`bg-gray-100 border-t border-gray-200 px-6 py-4 ${className}`}>
      <div className="max-w-7xl mx-auto text-center">
        <p className="text-sm text-gray-600">
          Generated by the PULSE System for the Municipal Local Governance Resource Center
        </p>
      </div>
    </div>
  );
}